swagger: "2.0"
info:
  title: SqlDB WS API
  description: |
    Generic database access API
  version: 1.0.0
  termsOfService: https://www.irt-saintexupery.com/
  contact:
    email: yves.cerezal@irt-saintexupery.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths: {}
definitions:
  Credential:
    title: Credential
    type: object
  json:
    title: json
    type: object
  "true":
    title: "true"
    type: object
